name: Build and Run CodeLens By Main Maven Jar

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Copy code-lens-sdk JAR
        run: mvn dependency:copy -Dartifact=com.cong:code-lens-sdk:1.0 -DoutputDirectory=./libs

      - name: Run Code Review
        run: java -jar ./libs/code-lens-sdk-1.0.jar
        env:
          GITHUB_TOKEN: ${{ secrets.CODE_TOKEN }}
          GLM_API_KEY: ${{ secrets.GLM_API_KEY }}